---
- name: Add IP to ~/.ssh/know_hosts
  shell: |
    IP=$(wget -q -O - ipinfo.io/ip)
    ssh-keygen -F $IP >/dev/null || ssh-keyscan -H $IP >> ~/.ssh/known_hosts
  ignore_errors: true

- name: Install deployer
  shell: |
    cd ~/{{ git_repository|splitext|first|split(':')|last }}
    composer require --dev deployer/deployer

- name: Copy deploy.yaml
  template:
    src: templates/deploy.template.yaml
    dest: "~/{{ git_repository|splitext|first|split(':')|last }}/deploy.yaml"
    force: false

- name: Add node and npm symlinks for non-login shell
  become: true
  shell: |
    rm -f /usr/bin/node
    rm -f /usr/bin/npm
    ln -s {{ ansible_env.HOME }}/.nvm/versions/node/{{ node_version }}/bin/node /usr/bin/
    ln -s {{ ansible_env.HOME }}/.nvm/versions/node/{{ node_version }}/bin/npm /usr/bin/

- name: Deploy application
  shell: |
    cd ~/{{ git_repository|splitext|first|split(':')|last }}
    vendor/bin/dep deploy {{ deploy_namespace }} -o local=true

- name: Remove node and npm symlinks
  become: true
  shell: |
    rm -f /usr/bin/node
    rm -f /usr/bin/npm
