---
- name: Setup github repository
  git:
    repo: "{{ git_repository }}"
    dest: "~/{{ git_repository|splitext|first|split(':')|last }}"
    force: yes
    accept_hostkey: yes
    version: "{{ git_branch }}"

- name: Clean untracked files
  shell: |
    cd ~/{{ git_repository|splitext|first|split(':')|last }}
    git clean -fd
