/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OnboardingIndexRouteImport } from './routes/onboarding/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as OnboardingStepsRouteImport } from './routes/onboarding/steps'
import { Route as OnboardingPostSetupRouteImport } from './routes/onboarding/post-setup'
import { Route as OnboardingInitRouteImport } from './routes/onboarding/init'
import { Route as AdminUsersRouteImport } from './routes/admin/users'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingIndexRoute = OnboardingIndexRouteImport.update({
  id: '/onboarding/',
  path: '/onboarding/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingStepsRoute = OnboardingStepsRouteImport.update({
  id: '/onboarding/steps',
  path: '/onboarding/steps',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingPostSetupRoute = OnboardingPostSetupRouteImport.update({
  id: '/onboarding/post-setup',
  path: '/onboarding/post-setup',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingInitRoute = OnboardingInitRouteImport.update({
  id: '/onboarding/init',
  path: '/onboarding/init',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin/users': typeof AdminUsersRoute
  '/onboarding/init': typeof OnboardingInitRoute
  '/onboarding/post-setup': typeof OnboardingPostSetupRoute
  '/onboarding/steps': typeof OnboardingStepsRoute
  '/admin': typeof AdminIndexRoute
  '/onboarding': typeof OnboardingIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin/users': typeof AdminUsersRoute
  '/onboarding/init': typeof OnboardingInitRoute
  '/onboarding/post-setup': typeof OnboardingPostSetupRoute
  '/onboarding/steps': typeof OnboardingStepsRoute
  '/admin': typeof AdminIndexRoute
  '/onboarding': typeof OnboardingIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin/users': typeof AdminUsersRoute
  '/onboarding/init': typeof OnboardingInitRoute
  '/onboarding/post-setup': typeof OnboardingPostSetupRoute
  '/onboarding/steps': typeof OnboardingStepsRoute
  '/admin/': typeof AdminIndexRoute
  '/onboarding/': typeof OnboardingIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin/users'
    | '/onboarding/init'
    | '/onboarding/post-setup'
    | '/onboarding/steps'
    | '/admin'
    | '/onboarding'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin/users'
    | '/onboarding/init'
    | '/onboarding/post-setup'
    | '/onboarding/steps'
    | '/admin'
    | '/onboarding'
  id:
    | '__root__'
    | '/'
    | '/admin/users'
    | '/onboarding/init'
    | '/onboarding/post-setup'
    | '/onboarding/steps'
    | '/admin/'
    | '/onboarding/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminUsersRoute: typeof AdminUsersRoute
  OnboardingInitRoute: typeof OnboardingInitRoute
  OnboardingPostSetupRoute: typeof OnboardingPostSetupRoute
  OnboardingStepsRoute: typeof OnboardingStepsRoute
  AdminIndexRoute: typeof AdminIndexRoute
  OnboardingIndexRoute: typeof OnboardingIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/': {
      id: '/onboarding/'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/steps': {
      id: '/onboarding/steps'
      path: '/onboarding/steps'
      fullPath: '/onboarding/steps'
      preLoaderRoute: typeof OnboardingStepsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/post-setup': {
      id: '/onboarding/post-setup'
      path: '/onboarding/post-setup'
      fullPath: '/onboarding/post-setup'
      preLoaderRoute: typeof OnboardingPostSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/init': {
      id: '/onboarding/init'
      path: '/onboarding/init'
      fullPath: '/onboarding/init'
      preLoaderRoute: typeof OnboardingInitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminUsersRoute: AdminUsersRoute,
  OnboardingInitRoute: OnboardingInitRoute,
  OnboardingPostSetupRoute: OnboardingPostSetupRoute,
  OnboardingStepsRoute: OnboardingStepsRoute,
  AdminIndexRoute: AdminIndexRoute,
  OnboardingIndexRoute: OnboardingIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
